import Head from 'next/head'
import { Space_Grotesk } from '@next/font/google'
import Navbar from '../components/blocks/Navbar'
import Landing from '../components/blocks/Landing'
import Proyect from '../components/blocks/Proyect'
import About from '../components/blocks/AboutMe'
import Footer from '../components/blocks/Footer'


const SpaceGrotesk = Space_Grotesk({ subsets: ['latin'] })

export default function Home() {
  return (
    <div className={`dark:bg-slate-900 ${SpaceGrotesk.className}`}>
      <Head>
        <title>Maikol aguilar</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="min-h-screen mx-auto relative max-w-screen-2xl grid place-content-center gap-40 dark:bg-slate-900">

        <Navbar />

        <Landing />
        <Proyect />
        <About />
        <Footer />
      </div>
    </div>
  )
}
